// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vufmkjgdujflcmpdusbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1Zm1ramdkdWpmbGNtcGR1c2J1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NzUzNTIsImV4cCI6MjA2MzU1MTM1Mn0.EBfUZ_31HONCHJBJKvN1AYA-vZOHTp4KYEpu_27PrbI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);